#!/usr/bin/env bash
#using case statement

count=1
while [ $count -le 20 ]; do
	echo "$count"
	case $count in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from italy"
	esac

	count=$((count + 1))
done
